apiVersion: apps/v1
kind: Deployment
metadata:
  name: heh-flask
  labels:
    app: heh-flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: heh-flask
  template:
    metadata:
      labels:
        app: heh-flask
    spec:
      containers:
        - name: heh-flask
          image: baajiinn/heh-flask:c5c2ec12776f47057c198fa0d48a0c378508a00a
          imagePullPolicy: IfNotPresent