name: CurrentTime

on:
  workflow_dispatch:

jobs:
  time:
    runs-on: ubuntu-latest

    steps:
    - name : Récurpérer l'heure actuelle
      id: time
      uses: josStorer/get-current-time@v2.1.2
      with:
        format: YYYY-MM-DD

    - name: Afficher la date
      run: |
        DATE=$(date -d "${{ steps.time.outputs.time }}" "+%d/%m/%Y")
        echo "Date actuelle : $DATE"
   
