name: Install Docker

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Installer Docker
      uses: papodaca/install-docker-action@v1

    - name: Connexion sur Docker Hub
      uses: docker/login-action@v3
      with:
        username: baajiinn
        password: ${{ secrets.MY_TOKEN }}

    - name: Création de l'image
      uses: docker/build-push-action@v6.18.0
      with:
        push: true
        tags: baajiinn/heh-flask:${{ github.sha }}

    - name: Mise à jour du mainfest Kubernetes with avec un nouveau tag sha
      run: |
        sed -i "s|image: baajiinn/heh-flask:.*|image: baajiinn/heh-flask:${{ github.sha }}|g" k8s/deployment.yml

    - name: Commit and push manifest update
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add k8s/deployment.yml
        git commit -m "chore: bump image tag to ${{ github.sha }}" || exit 0
        git push
